import Head from "next/head";
import type { FC,ReactNode } from "react";
import { StepBar } from "src/components/stepBar";

type Props = {
  children: ReactNode;
}

export const Layout: FC<Props> = (props) => {
  return (
    <>
      <Head>
        <title>valtio状態管理</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StepBar />
      <main>
        {props.children}
      </main>
    </>
  );
};
