import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import type { FC,ReactNode } from "react";
import type { SubmitHandler } from "react-hook-form";
import { useForm } from "react-hook-form";
import type { Inputs } from "src/interface/types";
import { changeForm } from "src/libs/changeForm";
import { formState } from "src/libs/state";
import { useSnapshot } from "valtio";

type Props = {
  children: ReactNode;
}

export const Layout: FC<Props> = (props) => {
  return (
    <>
      <Head>
        <title>valtio状態管理</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 my-20 mx-auto w-80 border">
        <h1 className="text-2xl text-center bg-blue-400">フォーム</h1>
        {props.children}
      </main>
    </>
  );
};
